# =============================================================================
#  Yazi — theme
# =============================================================================

[flavor]
dark  = "catppuccin-mocha"
light = "catppuccin-mocha"
