#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="SF Pro"
SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null"

PADDINGS=3

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

SHADOW=on

sketchybar --bar     height=50                                         \
                     color=$BAR_COLOR                                  \
                     shadow=$SHADOW                                    \
                     position=right                                     \
                     sticky=on                                         \
                     padding_right=18                                  \
                     padding_left=18                                   \
                     corner_radius=9                                   \
                     y_offset=10                                       \
                     margin=10                                         \
                     blur_radius=20                                    \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:14.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Semibold:13.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=11                 \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=$SHADOW

source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"

source "$ITEM_DIR/calendar.sh"

sketchybar --update

echo "sketchybar configuation loaded.."
