#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

blacklist = ["scratch"]
cache = true

[default_session]
startup_command = "nvim -c ':Telescope find_files'"
preview_command = "eza --all --git --icons --color=always {}"

[tui]
prompt = "> "
placeholder = "Filter sessions... "
show_icons = true

[[session]]
name = "home"
path = "~"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "nvim"

[[session]]
name = "goGreen"
path = "~/goGreen"

[[session]]
name = "MyAwesomeApp"
path = "~/Desktop/MyAwesomeApp"

[[session]]
name = "playground"
path = "~/Documents/Playground"

[[session]]
name = "downloads"
path = "~/Downloads"