#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[[session]]
name = "home"
path = "~"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "nvim"

[[session]]
name = "goGreen"
path = "~/goGreen"

[[session]]
name = "MyAwesomeApp"
path = "~/Desktop/MyAwesomeApp"

[[session]]
name = "playground"
path = "~/Documents/Playground"

[[session]]
name = "downloads"
path = "~/Downloads"